language: php

php:
  - 5.6
  - 7
  - hhvm

script:
  # note: not activating `--report-useless-tests` as we are currently having many tests with no assertions
  #- ./vendor/bin/phpunit --disallow-test-output --report-useless-tests --coverage-clover ./clover.xml
  - ./vendor/bin/phpunit --disallow-test-output --coverage-clover ./clover.xml

matrix:
  allow_failures:
    - php: hhvm
    - php: 7
